[package]
name = "kira-fastq"
description = "High-performance FASTQ reader and writer with mmap-first design. Supports plain, gzip, and BGZF inputs/outputs; optional multi-line parsing; explicit paired-end reading; sync and async APIs; optional `noodles-bgzf` interop."
version = "0.3.0"
edition = "2024"
rust-version = "1.95"
license = "MIT"
repository = "https://github.com/ARyaskov/kira-fastq"
keywords = [
    "bioinformatics",
    "genomics",
    "sequence-alignment"
]
categories = [
    "science",
    "science::bioinformatics",
    "science::bioinformatics::sequence-analysis",
    "command-line-utilities"
]

[dependencies]
memmap2 = "0.9"
miniz_oxide = "0.9"
memchr = "2.7"
crc32fast = "1.5"
flate2 = { version = "1.1", default-features = false, features = ["zlib-rs"] }

libdeflater = { version = "1.23", optional = true }

tokio = { version = "1", optional = true, default-features = false, features = ["io-util", "fs", "rt"] }
futures-util = { version = "0.3", optional = true, default-features = false, features = ["std"] }
async-compression = { version = "0.4", optional = true, default-features = false, features = ["tokio", "gzip"] }

noodles-bgzf = { version = "0.47", optional = true }

[dev-dependencies]
criterion = "0.8"
flate2 = "1.1"
crc32fast = "1.5"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "io-util", "fs"] }
futures = { version = "0.3", default-features = false, features = ["std", "executor"] }

[features]
default = []
gzip-validate = []
libdeflate = ["dep:libdeflater"]
async = ["dep:tokio", "dep:futures-util", "dep:async-compression"]
noodles-bgzf = ["dep:noodles-bgzf"]

[[bench]]
name = "newline"
harness = false

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "mmap_vs_gzip"
harness = false

[[bench]]
name = "end_to_end"
harness = false

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
should_implement_trait = "allow"
new_without_default = "allow"
